version: '3'

vars:
  CONTAINER_NAME: m32-sync-utility
  SRC_DIR: ./src

tasks:
  pull:
    desc: Syncs the "live" flows and package data from the running container back to the repo.
    cmds:
      - echo "Pulling live flows from {{.CONTAINER_NAME}}..."
      - podman cp {{.CONTAINER_NAME}}:/data/flows.json {{.SRC_DIR}}/flows.json
      - podman cp {{.CONTAINER_NAME}}:/data/package.json {{.SRC_DIR}}/package.json
      - echo "Done! You can now 'git add src/flows.json' to save your changes."

  build:
    desc: Rebuilds the container image locally using the Dockerfile in /containers/app.
    cmds:
      - podman compose build 
      - podman compose up -d
      - task: status

  status:
    desc: Quick check of the container health and current config.
    cmds:
      - podman ps --filter name={{.CONTAINER_NAME}}
      - echo "--- Current App Config ---"
      - podman exec {{.CONTAINER_NAME}} cat /data/mixer_config.json
  
  logs:
    desc: Follow the live logs from the mixer sync engine.
    cmds:
      - podman logs -f {{.CONTAINER_NAME}}

  rollback:
    desc: Reverts the container to a specific tagged version (e.g., task rollback VERSION=2026-01-05).
    vars:
      VERSION: '{{.VERSION | default "latest"}}'
    cmds:
      - echo "Rolling back to version {{.VERSION}}..."
      - podman pull ghcr.io/your-username/m32-sync-utility:{{.VERSION}}
      - |
        # Update the image tag in docker-compose temporarily or use an environment variable
        IMAGE_TAG={{.VERSION}} podman-compose up -d
      - echo "Rollback complete. Running version {{.VERSION}}."